### ISSUE TITLE
Solution v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#11]
The solution paragraph should state: How did you design and implement you solution?

**Comment by Jarlius** [comment]
Tidigare lösningsplan:

> We intend to develop our project on the ChipKIT Uno32 board, the Basic I/O shield, an
> external microphone and some speakers. We will use the buttons on the Basic I/O shield
> to control the recording and playback using interrupts. We will plug the microphone and
> the speakers in to the chipkit through some of its ports. We will develop everything in C
> and perhaps with some assembler code.

**Comment by simhel2** [comment]
We developed our game using the ChipKIT Uno32 board and the Basic I/O shield. Most of the code was written in C.  We used the buttons to control the movement in the game and the timer to control the pacing. To generate our "random" numbers we used a combination of user input and the timer.
