### ISSUE TITLE
Contributions v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#13]
This section should explain who did what of the two project members.

**Comment by Jarlius** [comment]
Tidigare bidragande:

> Simon will focus on connecting the Microphone and Speakers to the Basic I/O shield, and
> Jarl will focus on the C code necessary to store the soundfiles.

**Comment by simhel2** [comment]
ah juste vi måste hitta på hur vi delade upp det nu.

**Comment by simhel2** [comment]
kan skriva att du gjorde buttons och jag gjorde hitdetection och slumpalgoritm. sen delade vi på resten?

**Comment by simhel2** [comment]
eller nåt sånt

**Comment by simhel2** [comment]
Simon focused on the hit detection and generating a random algorithm that made the difficulty of the game be in line with our vision.
Jarl focused on making the buttons work in the way we intended (making sure every buttonpress only moved the player once etcetera) and designing and implementing the power-ups. The rest we wrote togheter.

**Comment by simhel2** [comment]
Stavfel fixade 
Simon focused on the hit detection and generating a random algorithm that made the difficulty of the game be in line with our vision.
Jarl focused on making the buttons work in the way we intended (making sure every button press only moved the player once etcetera) and designing and implementing the power-ups. We wrote the rest of the code together.
