### ISSUE TITLE
Reflections v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#14]
The last paragraph should include a few lines of reflections about the project.

**Comment by Jarlius** [comment]
Tidigare reflektioner:

> In the final abstract, we will discuss and reflect on what happened in the project.

**Comment by simhel2** [comment]
Borde vi skriva något om hur vi bytte projekt här?

**Comment by simhel2** [comment]
aaaasdf vet inte vad jag ska skriva fastnar
kan du ta denna ? @Jarlius 
skicka allt genom ett stavningsprogram innan du lämnar in oxå! annars är vi väl ganska klara om det inte finns invändningar hör av dig isf!

**Comment by Jarlius** [comment]
Fast du ville iofs inte att vi berättar om att vi var sena.
Känns dock som om det är bättre att erkänna, så får de bedömma projektet för vad det är

**Comment by Jarlius** [comment]
Det bör ju inte vara en så värst stor skam att erkänna att man inte hade mycket tid åt projektet heller, med tanke på hur ökänd årskurs 2 HT är för att ha mycket labbar

**Comment by simhel2** [comment]
Är okay med att säga att vi var sena menade att jag tycker att vi kan nämna att vi också kände att det inte var lika rewarding med projektet som vi tänkt oss från början heller med tanke på uppoffringarna vi trodde vi skulle behöva göra i ljudkvalitet.

**Comment by simhel2** [comment]
men lämna som det är annars är ju inte någon big deal

**Comment by Jarlius** [comment]
Nämnde att ljudkvalitén blev dålig i Requirements
