### ISSUE TITLE
Title of the project

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#2]
> The title must clearly state what the project is about.

Vårat projekt måste ha ett namn. Har du några idéer?

**Comment by Jarlius** [comment]
Speakophony
Soundify
Mic-to-Speak
Sounderbender

**Comment by Jarlius** [comment]
Från exempeldraft:
> A"Motion"Controlled"Snake"Game

Så vad sägs om: Mic-to-Speak - A Recording and Playback Device ?

**Comment by simhel2** [comment]
Mic-to-Speak - A Recording and Playback Device gillar jag vi kör på det låter proffsigt !
