### ISSUE TITLE
Objective and Requirements

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#3]
> These paragraphs should answer the questions: What should you project do and which are the main requirements?

Ska projektet vara ljudhantering eller ett spel?

**Comment by Jarlius** [comment]
Från exempeldraften: 

> Objective and Requirements. The purpose of this project is to develop the classic
> “snake” game on an embedded platform with limited resources. In this game, a snake is
> growing on the screen, and the challenge for the players is to make the tail of the snake
> grow as long as possible. The main must requirements for the game are as follows:
> • The game must support multi-player mode and high score lists.
> • It must support different difficulty levels.
> • The user must be able to control the game with the buttons on the ChipKIT board.
> Optional features that may be included, if time allows:
> • To control the game using an external accelerometer. The sensor is communicating
> with the main board using SPI or I2
> C.
> • To use the A/D converter together with an external speaker to generate sounds for
> the game.
> • Enable multiplayer mode where two players with different ChipKIT boards can
> play with each other. The UART will be used for serial communication.

**Comment by simhel2** [comment]
**Objective and requirements.** 

The purpose of this project is to develop a simple audio record and playback system. A button will be pressed and a mic will start recording whatever sound there is, then the sound will play back to the user. 
The main must requirements for the project:

- The user must be able to control the recording with buttons on the ChipKIT board.
- Audio playback of the recording after a set time.
- The system must work with a mic and speakers.

Optional features that may be included if time allows:
- Voice changer features controlled through the ChipKIT board.
- More control of recording time and when the playback starts using the ChipKIT board.

**Comment by Jarlius** [comment]
Haha, jag höll också på att skriva.
Det enda jag skulle tillägga är att Audio playback kanske ska kontrolleras av en knapp också, så att man spelar upp senaste recording

**Comment by simhel2** [comment]
Sure kan flytta 
"More control of recording time and when the playback starts using the ChipKIT board." 
och skriva om den lite från optional features till must have features typ:

Objective and requirements.

The purpose of this project is to develop a simple audio record and playback system. A button will be pressed and a mic will start recording whatever sound there is, then the sound will play back to the user. 
The main must requirements for the project:

- The user must be able to control the recording with buttons on the ChipKIT board.
- Audio playback of the recording.
- Control of the recording time and when playback start using the ChipKIT board.
- The system must work with a mic and speakers.

Optional features that may be included if time allows:
- Voice changer features controlled through the ChipKIT board.

**Comment by Jarlius** [comment]
Ah, men så också lägga till display som optional feature

**Comment by simhel2** [comment]
Objective and requirements.

The purpose of this project is to develop a simple audio record and playback system. A button will be pressed and a mic will start recording whatever sound there is, then the sound will play back to the user. 
The main must requirements for the project:

- The user must be able to control the recording with buttons on the ChipKIT board.
- Audio playback of the recording.
- Control of the recording time and when playback start using the ChipKIT board.
- The system must work with a mic and speakers.

Optional features that may be included if time allows:

- Voice changer features controlled through the ChipKIT board.
- Display of useful stuff like voice changer mode, current recording time and last recording lenght.

**Comment by simhel2** [comment]
behöver renskrivas lite obs

**Comment by Jarlius** [comment]
Mm men annars blir det perfekt
