### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#4]
> The solution paragraph should state: How did you design and implement you solution?

Det här beror på vilket projekt vi väljer, men förutsatt att vi väljer ljud så blir det viktigaste hur man kopplar mikrofon :microphone: och högtalare :speaker: till chippet

Också hur ljudet från mikrofonen lagras innan det spelas upp till högtalare kan vara viktigt att lista ut.

**Comment by Jarlius** [comment]
Från exempeldraften:
> Solution. We intend to develop our project on the ChipKIT Uno32 board together with
> the Basic I/O shield. We will use the small display on the Basic I/O shield to display the
> game and use the slide switches to move in the vertical direction, and the push buttons to
> move in the horizontal direction. We will use interrupts triggered by the built in timer to
> update the screen and control the speed of the game. All the development is done using
> the MCB32tools and all code is written in C. 
Så kanske vi beskriver här hur basic recording fungerar

**Comment by simhel2** [comment]
We intend to develop our project on the ChipKIT Uno32 board, the Basic I/O shield, an external mircophone and some speakers. We will use the buttons on the Basic I/O shield to control the recording and playback using interrupts. We will develop everything in C and perhaps with some assembler code.

**Comment by Jarlius** [comment]
Aa, för de kommer nog ge tips om hur man gör för att koppla ihop allt rätt

**Comment by simhel2** [comment]
Tror btw att vi kommer att behöva mörda kablarna till högtalaren och miccen vi använder. Skrev bara in det väldigt generiskt så förstår det kanske att vi behöver hjälp?


We intend to develop our project on the ChipKIT Uno32 board, the Basic I/O shield, an external mircophone and some speakers. We will use the buttons on the Basic I/O shield to control the recording and playback using interrupts. **We will plug the microphone and the speakers in to the chipkit through some of its ports.** We will develop everything in C and perhaps with some assembler code.

**Comment by Jarlius** [comment]
Jag råkar ha en riktigt kass mikrofon, som jag borde ha bytit ut för åratal sen.
