### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#5]
> The verification paragraph should answer: How did you test or verify that you solution is correct?

Den här borde ju vara ganska lätt eftersom man hör om högtalaren :speaker: spelar upp ljud, duh

**Comment by simhel2** [comment]
Our system should be quite simple to test, depending on how many features we install since we can listen to the sound that is played back and see if it works correctly. However we must also test how much memory the audio recordings take and be sure not to let the users use more memory than we can spare this testing can be done??????.

**Comment by Jarlius** [comment]
Kanske såhär:
Att mikrofonen fungerar visas på att data ändras dit vi skickar den när tiden går.
Idé -> vi kanske styr tiden för hur länge mikrofonen får vara på med storleken på ljudets array?
Speaker -> denna del är det lätta att testa, funkar det så kommer ljud igenom, annars är det tyst

**Comment by simhel2** [comment]
Asw tror vi borde testa i verification hur länge vi egengliten kan recorda sen välja en lägra siffra som vi låser det till när folk faktiskt använder den känns rimligare? typ pre verify eller nåt.
Precis det blir lätt att testa allt som man "ser från utsidan vad som händer" men minnet är väl undantaget till det tänkte jag

**Comment by Jarlius** [comment]
Vi behöver inte gissa rätt nu, för de rättar oss förmodligen när vi får feedback. Men att om man hänger en array till att innehålla ljuddata känns enkelt, och säkrare än att låta den löpa amok och läggas på stacken

**Comment by simhel2** [comment]
Tror du att vi behöver bry oss om ljudformat ?

**Comment by simhel2** [comment]
asw typ mp3 64 kb/s och flac har ju lite olika krav, vet inte hur stödet i C är alls eller hur stort minnet är på chipkittet tbh

**Comment by Jarlius** [comment]
Sånt har jag ingen aning om, om jag ska vara ärlig. Hoppas att det inte kommer behövas..

**Comment by simhel2** [comment]
verkar som om det är en grej om man ska göra om en analog signal (kommer från miccen) till en digital (lagras på hårddiskar) vi kanske måste ha en ADC (analog till digital converter) på något sätt?

**Comment by simhel2** [comment]
och kanske en DAC (digital till analog converter) för högtalaren?

**Comment by simhel2** [comment]
ljudkort i datorer har ju redan sånt men tror inte chipkittet har det

**Comment by simhel2** [comment]
http://macao.communications.museum/eng/exhibition/secondfloor/MoreInfo/ADConverter.html

**Comment by simhel2** [comment]
jag har iofs en extern dac/adc men den har usb till datorn vet inte hur vi gör där?

**Comment by simhel2** [comment]
hahah känns som om spelet vore lättare xD

**Comment by Jarlius** [comment]
Three parts needs to be tested; Microphone, Memory and Speakers.
The Microphone can be considered operational when it changes data in designated memory.
Memory itself is a bit trickier, and will presumably be stored as an array with a currently unknown datatype.
The Speaker is the easiest to verify, as it will play audio when it's working.

**Comment by Jarlius** [comment]
Joo det är lättare, men känns som att man lär sig mer av en sån här uppgift än ett spel som man gjort flera gånger tidigare

**Comment by simhel2** [comment]
mmh sant mer I/O mycket bättre för att lära sig.

**Comment by simhel2** [comment]
aja vi kör på det där du skrev fungerar nog det fattar nog att vi behöver hjälp då!

**Comment by Jarlius** [comment]
Okej, jag ska bara fixa pdf i latex (har inte openoffice på linux :( )

**Comment by simhel2** [comment]
yes är vi klara nu? reflektionsbiten skriver vi inget i eller ah typ inget som dom gjorde eller?

**Comment by simhel2** [comment]
arbetsfördelning var det oxå juste

**Comment by Jarlius** [comment]
Jaa, men det gör vi en ny issue
