### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#6]
Sista delen i vår draft.
I exempeldraft: 
> We intend to divide the work in the following way: Sven will focus on
> the development of the graphical display and the sound generation. Anna will work on
> the program logic, the main game engine, and the interaction with the accelerometer. The
> final division of work will be explained in the final report.

Går det att dela upp arbetet på nåt sätt redan nu?

**Comment by Jarlius** [comment]
Och juste sen behöver jag ditt personnummer för framsidan tydligen

**Comment by simhel2** [comment]
940903 8636
hmm är svårt att dela upp detta imo ?

**Comment by Jarlius** [comment]
Simon will focus on connecting the Microphone and Speakers to the Basic I/O shield, and Jarl will focus on the C code necessary to store the soundfiles.

vad sägs om detta?

**Comment by Jarlius** [comment]
Vi behöver ju inte följa det till punkt och pricka heller

**Comment by simhel2** [comment]
sure vi skriver så sen kör vi bara på som det blir!

**Comment by simhel2** [comment]
Känns som att det fungarade bra att arbeta såhär gillar det!

**Comment by Jarlius** [comment]
Jaa det blir bra struktur :)
Har pushat pdf, du kan kolla igenom om du hittar några fel

**Comment by Jarlius** [comment]
Sen fick vi tid kl 11.00 imorgon, fungerar det för dig?

**Comment by simhel2** [comment]
fungerar för mig vart hittar jag pdfen?
du skickade din variant till mig på skolmailen va?

**Comment by Jarlius** [comment]
Pdfen är i code-fliken, till vänster om Issues.
Men du måste navigera till den via draft -> draft.pdf, klickar du på commitmeddelandet kommer du fel

**Comment by Jarlius** [comment]
Och yes, skickade den på skolmailen

**Comment by simhel2** [comment]
kikar nu!

**Comment by simhel2** [comment]
jag ser några felstavningar kör det genom ett stavningsprogram online!
vi kanske ska byta ut "useful stuff" mot typ "useful information"

**Comment by Jarlius** [comment]
Fick lite förhinder, har snyggat till det nu.
Kvar är bara att skicka in pdfen :tada:
