### ISSUE TITLE
Bra länkar till kablar

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#7]
Något som detta kanske är värt att kolla?

> https://www.conrad.se/USB-2.0-Anslutningskabel-Akasa-%5B1x-USB-2.0-A-hane-1x-USB-2.0-intern-4-pol-hane%5D-0.40-m-Svart.htm?websale8=conrad-swe&pi=976294

**Comment by simhel2** [comment]
http://embedded-lab.com/blog/chipkit-tutorial-2-serial-communication-with-pc/ 
hur man använder usb:n som är inbyggd för att kommunicera med pc om annat än källkod.

**Comment by simhel2** [comment]
http://stackoverflow.com/questions/10397272/wav-file-convert-to-byte-array-in-java 
Wav -> byte array, saknar dock mic grej

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/com/sun/media/sound/WaveFileReader.java 
någon rekommenderade denna, förstod den inte riktigt.
 
https://processing.org/tutorials/sound/
roliga ljudgrejer. (piano tangentbord) och annan kod för saker som jag inte vet om vi kommer behöva göra.

**Comment by simhel2** [comment]
http://xmodulo.com/how-to-capture-microphone-input-to-wav-format-file.html 
mic to wav.

**Comment by simhel2** [comment]
http://xmodulo.com/how-to-capture-microphone-input-to-wav-format-file.html 
enligt denna så verkar data kunna sparas som 16 bitars signed big endian. kanske kan komma åt det med C utan att hålla på och anstränga sig så mycket.
