### ISSUE TITLE
Title of the Project v2

### ISSUE THREAD

**Issue by Jarlius** [Jarlius/Dtek-Project#9]
The title must clearly state what the project is about.

**Comment by Jarlius** [comment]
Tidigare titeln för projektet:
> Mic-to-Speak - A Recording and Playback Device

**Comment by simhel2** [comment]
Förslag:
Return of the X:es - A Simple Side-Scrolling Game.

Första delen är förhandlingsbar men tycker  - A Simple Side-Scrolling Game. är trevligt oavsett

**Comment by Jarlius** [comment]
Namnet skulle kunna bli X-terminate
